import { type LocalizedSampleContent, type SampleTripId } from '@/lib/sample-catalog/base'

export const sampleCatalogEn = {
  'family-springs': {
    theme: 'Family',
    seedTitle: 'Family Springs in the Upper Galilee',
    plannerNotes: 'Keep this calm, child-friendly, and easy to execute on a spontaneous day out.',
    title: 'Upper Galilee Springs for Families',
    summary: 'A calm day plan with easy nature stops, water views, and enough flexibility for kids and parents alike.',
    audience: 'Best for families, grandparents, and relaxed weekend pacing',
    durationNote: 'Easy one-day outing',
    coverImageUrl: '',
    highlights: ['Shady spring stop', 'Short scenic walks', 'Lunch-friendly pacing'],
    badges: ['Family-friendly', 'Kids-friendly', 'Stroller-friendly'],
    vibe: 'Green, calm, and easy to say yes to.',
    pace: 'Slow and flexible.',
    practicalNotes: ['Start early before the heat builds.', 'Keep one simple food stop in the middle.'],
    bring: ['Water shoes', 'Spare clothes', 'Sun hats'],
    routeOutline: [
      { title: 'Shaded spring', summary: 'Begin with an easy water stop.' },
      { title: 'Short loop', summary: 'Add one gentle scenic walk.' },
      { title: 'Lunch and finish', summary: 'End close to food and the car.' },
    ],
    whyItWorks: 'It feels manageable from the first stop to the last.',
  },
  'accessible-sunset': {
    theme: 'Accessible',
    seedTitle: 'Accessible Sunset Escape by the Sea',
    plannerNotes: 'Prioritize smooth access, short transfers, shaded stops, and realistic low-mobility pacing.',
    title: 'Accessible Sunset by the Carmel Coast',
    summary: 'A low-friction route built around smooth access, scenic sea moments, and comfortable timing.',
    audience: 'Best for accessible planning and wheelchair-friendly travel',
    durationNote: 'Gentle one-day route',
    coverImageUrl: '',
    highlights: ['Smooth access points', 'Short transfers', 'Sunset viewpoint'],
    badges: ['Accessible', 'Wheelchair-friendly', 'Low-mobility'],
    vibe: 'Open air, sea light, and thoughtful comfort.',
    pace: 'Gentle and steady.',
    practicalNotes: ['Check parking and accessible entry before leaving.', 'Avoid stacking too many stops into one afternoon.'],
    bring: ['Water bottle', 'Layer for sea breeze', 'Phone charger'],
    routeOutline: [
      { title: 'Accessible coastal entry', summary: 'Start with an easy sea-facing stop.' },
      { title: 'Optional second stop', summary: 'Only add another stop if the pace still feels good.' },
      { title: 'Sunset close', summary: 'Finish with a simple accessible lookout.' },
    ],
    whyItWorks: 'It respects comfort and movement instead of forcing a generic route.',
  },
  'romantic-vineyards': {
    theme: 'Romantic',
    seedTitle: 'Romantic Judean Hills Weekend',
    plannerNotes: 'Make it intimate, scenic, and relaxed with sunset moments and memorable food stops.',
    title: 'Romantic Judean Hills Weekend',
    summary: 'A scenic, slower-paced escape with viewpoints, winery energy, and a polished date-night feel.',
    audience: 'Best for couples and slower premium weekend plans',
    durationNote: '2-3 day escape',
    coverImageUrl: '',
    highlights: ['Golden-hour outlooks', 'Food stop moments', 'Relaxed scenic pacing'],
    badges: ['Romantic', 'Scenic', 'Weekend'],
    vibe: 'Warm, intimate, and unrushed.',
    pace: 'Slow and polished.',
    practicalNotes: ['Keep the first day light.', 'Use one sunset or winery stop as the emotional anchor.'],
    bring: ['Light jacket', 'Comfortable shoes', 'Camera'],
    routeOutline: [
      { title: 'Arrival with scenery', summary: 'Open somewhere that immediately shifts the mood.' },
      { title: 'Food and outlook rhythm', summary: 'Move through one or two strong stops.' },
      { title: 'Evening anchor', summary: 'Close with one memorable evening moment.' },
    ],
    whyItWorks: 'It balances atmosphere with simple logistics.',
  },
  'spontaneous-waterfall': {
    theme: 'Water',
    seedTitle: 'Spontaneous Waterfall Escape',
    plannerNotes: 'Keep it flexible, fast to start, and strong on water views and easy logistics.',
    title: 'Spontaneous Waterfall Day Trip',
    summary: 'A fast-start escape with waterfalls, splashy scenery, and simple route logic.',
    audience: 'Best for short-notice plans and refreshing day trips',
    durationNote: 'Quick one-day adventure',
    coverImageUrl: '',
    highlights: ['Waterfall energy', 'Easy launch logistics', 'Photo-worthy viewpoints'],
    badges: ['Spontaneous', 'Water-based', 'Day trip'],
    vibe: 'Fresh, active, and rewarding fast.',
    pace: 'Moderate but efficient.',
    practicalNotes: ['Leave early enough for parking.', 'Keep the route to a few high-value stops.'],
    bring: ['Water and snacks', 'Grippy shoes', 'Towel'],
    routeOutline: [
      { title: 'Direct launch', summary: 'Go straight to the strongest waterfall stop.' },
      { title: 'Second scenic payoff', summary: 'Add one nearby viewpoint or short trail.' },
      { title: 'Simple return', summary: 'Finish with food or coffee before heading back.' },
    ],
    whyItWorks: 'The reward arrives quickly, which is exactly what a spontaneous day needs.',
  },
  'photo-desert': {
    theme: 'Photography',
    seedTitle: 'Photography Sunrise in the Negev',
    plannerNotes: 'Focus on golden-hour timing, wide viewpoints, practical packing notes, and pacing for photographers.',
    title: 'Negev Sunrise for Photographers',
    summary: 'A desert route tuned around timing, viewpoints, packing logic, and golden-hour photography.',
    audience: 'Best for photographers, sunrise chasers, and scenic desert pacing',
    durationNote: '2-3 day photo route',
    coverImageUrl: '',
    highlights: ['Sunrise timing', 'Wide desert vistas', 'Packing-focused notes'],
    badges: ['Photography', 'Sunrise', 'Scenic'],
    vibe: 'Quiet, cinematic, and anchored by early light.',
    pace: 'Measured and intentional.',
    practicalNotes: ['Choose one main sunrise viewpoint.', 'Plan shade, water, and charging before open areas.'],
    bring: ['Camera kit', 'Tripod', 'Extra water'],
    routeOutline: [
      { title: 'Pre-dawn setup', summary: 'Reach the first viewpoint before sunrise.' },
      { title: 'Mid-morning movement', summary: 'Shift to one or two additional lookouts.' },
      { title: 'Rest and evening option', summary: 'Recover midday, then decide on sunset.' },
    ],
    whyItWorks: 'Photography days are about timing more than volume.',
  },
  'dog-friendly-coast': {
    theme: 'Dog-friendly',
    seedTitle: 'Dog-Friendly Coastal Reset',
    plannerNotes: 'Keep it dog-friendly, easy to park, and gentle on distance with practical stop recommendations.',
    title: 'Dog-Friendly Coastal Reset',
    summary: 'A relaxed coastal plan with easy access, practical stops, and pacing that works for dogs and humans.',
    audience: 'Best for dog owners and easy-going coastal escapes',
    durationNote: 'Easy one-day reset',
    coverImageUrl: '',
    highlights: ['Simple parking', 'Gentle walking distance', 'Flexible stop suggestions'],
    badges: ['Dog-friendly', 'Easy', 'Coastal'],
    vibe: 'Light, breezy, and practical.',
    pace: 'Easy and forgiving.',
    practicalNotes: ['Choose breezy or shaded walking segments.', 'Plan water and rest stops from the start.'],
    bring: ['Water for you and the dog', 'Leash and bags', 'Towel for the car'],
    routeOutline: [
      { title: 'Easy seaside start', summary: 'Open with a simple coastal stretch.' },
      { title: 'Flexible middle stop', summary: 'Add a cafe, lookout, or shaded break.' },
      { title: 'Gentle finish', summary: 'Wrap up somewhere with easy parking.' },
    ],
    whyItWorks: 'It respects weather, dog logistics, and real-world energy.',
  },
} satisfies Record<SampleTripId, LocalizedSampleContent>
